import Image from "next/image";
import { generateClient } from "aws-amplify/api";
import { withAuthenticator } from "@aws-amplify/ui-react";
import config from "../../src/amplifyconfiguration.json";
import { Amplify } from "aws-amplify";
import { createTodo, updateTodo, deleteTodo } from "@/graphql/mutations";
import { getTodo, listTodos } from "@/graphql/queries";
import { Metadata } from "next";
Amplify.configure(config);
const client = generateClient();
export const metadata: Metadata = {
  title: "SERVERLESS TOO App",
  description: "Generated by create next app",
};
export function getDateAndTIme() {
  const renderedAt = new Date();
  const formattedBuildDate = renderedAt.toLocaleDateString("en-US", {
    dateStyle: "long",
  });
  const formattedBuildTime = renderedAt.toLocaleTimeString("en-US", {
    timeStyle: "long",
  });
  return {
    props: {
      renderedAt: ` ${formattedBuildDate} at ${formattedBuildTime} `,
    },
  };
}
async function Home({ signOut, user, renderedAt }) {
  const newTodo = await client.graphql({
    query: createTodo,
    variables: {
      input: {
        title: "my first todo",
        completed: true,
      },
    },
  });
  const getTodo = await client.graphql({
    query: listTodos,
  });
  const changeTodo = await client.graphql({
    query: updateTodo,
    variables: {
      input: {
        id: "8ff644b7-f881-4d6f-ae61-d51a3fa81813",
        title: "my first todo updated",
        completed: true,
      },
    },
  });
  const removeTodo = await client.graphql({
    query: deleteTodo,
    variables: {
      input: {
        id: "8ff644b7-f881-4d6f-ae61-d51a3fa81813",
      },
    },
  });

  console.log(newTodo.data.createTodo);
  return (
    <>
      <main className="flex min-h-screen flex-col items-center justify-between p-24">
        <h1>Hello world</h1>
        <h2 className="bg-orange-500 text-black text-2xl font-bold text-center py-2 px-4 rounded-lg ">
          logged in as {user.username}
        </h2>
        <button onClick={signOut}>Sign out</button>
        <p>This page was server-side rendered on {renderedAt}.</p>
      </main>
    </>
  );
}

export default withAuthenticator(Home);
